In [83]:
# Import the pandas package, then use the "read_csv" function to read
# the labeled training data
import random
import numpy as np
import matplotlib.pyplot as plt
import platform
import pdb 
import math
import pandas as pd       

train = pd.read_csv("train.tsv", header=0, \
                    delimiter="\t", quoting=3)

train.shape
train.columns.values
print (set(train["Sentiment"]))
print (train.shape)
print(train["Phrase"][1])

{0, 1, 2, 3, 4}
(156060, 4)
A series of escapades demonstrating the adage that what is good for the goose


In [6]:
# Import BeautifulSoup into your workspace
from bs4 import BeautifulSoup             

# Initialize the BeautifulSoup object on a single movie review     
example1 = BeautifulSoup(train["Phrase"][0])  

# Print the raw review and then the output of get_text(), for 
# comparison
print (train["Phrase"][0])
print (example1.get_text())

A series of escapades demonstrating the adage that what is good for the goose is also good for the gander , some of which occasionally amuses but none of which amounts to much of a story .
A series of escapades demonstrating the adage that what is good for the goose is also good for the gander , some of which occasionally amuses but none of which amounts to much of a story .


In [7]:
import re
# Use regular expressions to do a find-and-replace
letters_only = re.sub("[^a-zA-Z]",           # The pattern to search for
                      " ",                   # The pattern to replace it with
                      example1.get_text() )  # The text to search
print (letters_only)
lower_case = letters_only.lower()        # Convert to lower case
words = lower_case.split()               # Split into words


A series of escapades demonstrating the adage that what is good for the goose is also good for the gander   some of which occasionally amuses but none of which amounts to much of a story  


In [8]:
import nltk
nltk.download('stopwords')  # Download text data sets, including stop words
from nltk.corpus import stopwords # Import the stop word list
print (stopwords.words("english") )
# Remove stop words from "words"
words = [w for w in words if not w in stopwords.words("english")]
print (words)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'ea

In [0]:
def review_to_words( raw_review ):
    # Function to convert a raw review to a string of words
    # The input is a single string (a raw movie review), and 
    # the output is a single string (a preprocessed movie review)
    #
    # 1. Remove HTML
    review_text = BeautifulSoup(raw_review).get_text() 
    #
    # 2. Remove non-letters        
    letters_only = re.sub("[^a-zA-Z]", " ", review_text) 
    #
    # 3. Convert to lower case, split into individual words
    words = letters_only.lower().split()                             
    #
    # 4. In Python, searching a set is much faster than searching
    #   a list, so convert the stop words to a set
    stops = set(stopwords.words("english"))                  
    # 
    # 5. Remove stop words
    meaningful_words = [w for w in words if not w in stops]   
    #
    # 6. Join the words back into one string separated by space, 
    # and return the result.
    return( " ".join( meaningful_words ))  
    clean_review = review_to_words( train["review"][0] )
    print (clean_review)
 


In [97]:


# Initialize an empty list to hold the clean reviews
clean_train_reviews = []


filter_train=train.loc[(train["Sentiment"]==4)|(train["Sentiment"]==0)]
print(filter_train.head())

# Get the number of reviews based on the dataframe column size
num_reviews = filter_train["Phrase"].size
print(num_reviews)
filter_train = filter_train.reset_index()
print(filter_train["Phrase"][1])

# Loop over each review; create an index i that goes from 0 to the length
# of the movie review list 
for i in range( 0, num_reviews ):
    # Call our function for each one, and add the result to the list of
    # clean reviews
  
    clean_train_reviews.append( review_to_words( filter_train["Phrase"][i] ) )
  # print(clean_train_reviews.shape)

     PhraseId  ...  Sentiment
63         64  ...          4
66         67  ...          4
74         75  ...          4
77         78  ...          4
101       102  ...          0

[5 rows x 4 columns]
16278
quiet , introspective and entertaining independent


In [98]:
print("Creating the bag of words...\n")
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the "CountVectorizer" object, which is scikit-learn's
# bag of words tool.  
vectorizer = CountVectorizer(analyzer = "word",   \
                             tokenizer = None,    \
                             preprocessor = None, \
                             stop_words = None,   \
                             max_features = 5000) 

# fit_transform() does two functions: First, it fits the model
# and learns the vocabulary; second, it transforms our training data
# into feature vectors. The input to fit_transform should be a list of 
# strings.
train_data_features = vectorizer.fit_transform(clean_train_reviews)

# Numpy arrays are easy to work with, so convert the result to an 
# array
train_data_features = train_data_features.toarray()
print (train_data_features)

Creating the bag of words...

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [99]:
# Take a look at the words in the vocabulary
vocab = vectorizer.get_feature_names()
print (vocab)

['abandon', 'ability', 'able', 'abroad', 'absolute', 'absolutely', 'absorbing', 'abstract', 'absurd', 'absurdity', 'absurdly', 'abundant', 'academy', 'accents', 'accept', 'acceptable', 'accessible', 'accident', 'accidental', 'acclaim', 'accomplish', 'accomplished', 'accomplishes', 'accomplishment', 'accomplishments', 'account', 'accurate', 'ace', 'acerbic', 'ache', 'achievement', 'achieves', 'achingly', 'across', 'act', 'acted', 'acting', 'action', 'activities', 'actor', 'actors', 'actress', 'actresses', 'acts', 'actual', 'actually', 'acute', 'adam', 'adaptation', 'adaptations', 'adapted', 'add', 'added', 'adding', 'addition', 'adds', 'admirable', 'admire', 'admission', 'admit', 'adolescent', 'adorably', 'adorns', 'adrenalin', 'adrenaline', 'adult', 'adults', 'adventure', 'adventures', 'adventurous', 'advised', 'aerial', 'aesthetic', 'affair', 'affected', 'affecting', 'affection', 'affirming', 'affirms', 'affleck', 'afraid', 'african', 'afterwards', 'age', 'agency', 'agenda', 'agent', 

In [105]:
###train data
X=train_data_features
y=filter_train["Sentiment"]

from sklearn.model_selection import train_test_split
X_train, x_test,y_train,y_test=train_test_split(X,y,
                                          test_size=0.3,random_state=1)

from sklearn.linear_model import LogisticRegression

logmodel=LogisticRegression()
logmodel.fit(X_train,y_train)
prediction=logmodel.predict(x_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,prediction)


0.9252661752661753